name: Upload to wemips.ralfgerlich.biz

on:
  push:
    branches: [ master ]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install jsduck
        run: gem install jsduck
      - name: Build documentation
        run: jsduck --builtin-classes -o docs --welcome=using_WeMips.html --head-html='<link rel="stylesheet" href="../css/weMipsStyle.css" type="text/css">'
      - name: Deploy the documentation to the server
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          protocol: ftps
          server: ${{ secrets.server }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          server-dir: ${{ secrets.target_dir }}
          security: strict
          exclude: "[**/.git*, **/.git*/**, release, master]"
