name: Upload to wemips.ralfgerlich.biz

on:
  push:
    branches: [ master ]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm ci
      - name: Build documentation
        run: npm run build-doc
      - name: Deploy package to the server
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          protocol: ftps
          server: ${{ secrets.server }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          server-dir: ${{ secrets.target_dir }}
          security: strict
          exclude: "[**/.git*, **/.git*/**, node_modules]"
